/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrintPreviewDialog.java
 *
 * Created on 07-feb-2010, 7:36:25
 */

package es.atareao.caps.gui;

import com.sun.pdfview.PDFFile;
import es.atareao.alejandria.gui.ErrorDialog;
import es.atareao.alejandria.gui.ExtensionFilter;
import es.atareao.alejandria.lib.Convert;
import es.atareao.alejandria.lib.FileUtils;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author atareao
 */
public class PrintPreviewDialog extends javax.swing.JDialog {

    /** Creates new form PrintPreviewDialog */
    public PrintPreviewDialog(java.awt.Frame parent,File document,File defaultDir) {
        super(parent, true);
        initComponents();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(Convert.toInt(pantalla.width * 0.9), Convert.toInt(pantalla.height * 0.9));
        this.setLocationRelativeTo(null);
        this._document=document;
        this._defaultDir = defaultDir;
        try {
            RandomAccessFile raf = new RandomAccessFile(document, "r");
            FileChannel channel = raf.getChannel();
            ByteBuffer buf = channel.map(FileChannel.MapMode.READ_ONLY, 0, channel.size());
            this._pdf = new PDFFile(buf);
            this.jTotalPages.setText(" / "+Convert.toString(this.getHojas()));
            this.setPage(1);
        } catch (FileNotFoundException ex) {
            ErrorDialog.manejaError(ex);
        } catch (IOException ex) {
            ErrorDialog.manejaError(ex);
        }
    }
    private int getHojas(){
        return this._pdf.getNumPages();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jPageNumber = new es.atareao.alejandria.gui.JNumericField();
        jTotalPages = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jImage1 = new es.atareao.alejandria.gui.JImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caps - Presentación Preliminar");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(32767, 50));
        jToolBar1.setMinimumSize(new java.awt.Dimension(12, 50));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_exit.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_save.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_arrow_first.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_arrow_left.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_arrow_right.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_arrow_last.png"))); // NOI18N
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);
        jToolBar1.add(jSeparator3);

        jPageNumber.setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.background"));
        jPageNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPageNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPageNumber.setMaximumSize(new java.awt.Dimension(44, 44));
        jPageNumber.setMinimumSize(new java.awt.Dimension(44, 44));
        jPageNumber.setPreferredSize(new java.awt.Dimension(60, 30));
        jPageNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPageNumberKeyPressed(evt);
            }
        });
        jToolBar1.add(jPageNumber);

        jTotalPages.setText(" / 0");
        jTotalPages.setOpaque(true);
        jTotalPages.setPreferredSize(new java.awt.Dimension(60, 30));
        jToolBar1.add(jTotalPages);
        jToolBar1.add(jSeparator4);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_zoom_plus.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/atareao/img/png/button_zoom_less.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        getContentPane().add(jToolBar1);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setDoubleBuffered(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 1000));

        jImage1.setMinimumSize(new java.awt.Dimension(10, 1000));
        jImage1.setPreferredSize(new java.awt.Dimension(100, 1000));
        jScrollPane1.setViewportView(jImage1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ExtensionFilter ef = new ExtensionFilter("*.pdf",".pdf");
        JFileChooser jfc = new JFileChooser(this._defaultDir);
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.setFileFilter(ef);
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        if (JFileChooser.APPROVE_OPTION == jfc.showSaveDialog(this)) {
            File file = jfc.getSelectedFile();
            if (!file.getAbsolutePath().endsWith(".pdf")) {
                file = new File(file.getAbsolutePath() + ".pdf");
            }
            try {
                FileUtils.copy(_document, file);
                System.out.println("COPIADO");
            } catch (FileNotFoundException ex) {
                ErrorDialog.manejaError(ex);
            } catch (IOException ex) {
                ErrorDialog.manejaError(ex);
            }
        }
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setZoom(Convert.toInt(_zoom*1.1));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setZoom(Convert.toInt(_zoom*0.9));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setPage(1);
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int page=this.getPage()-1;
        if(page<1){
            page=1;
        }
        this.setPage(page);
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int page=this.getPage()+1;
        if(page>this.getHojas()){
            page=this.getHojas();
        }
        this.setPage(page);
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setPage(this.getHojas());
}//GEN-LAST:event_jButton8ActionPerformed

    private void jPageNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPageNumberKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            int page=(int)this.jPageNumber.getDouble();
            if(page<1){
                page=1;
            }
            if(page>this.getHojas()){
                page=this.getHojas();
            }
            this.setPage(page);
        }
}//GEN-LAST:event_jPageNumberKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private es.atareao.alejandria.gui.JImage jImage1;
    private es.atareao.alejandria.gui.JNumericField jPageNumber;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jTotalPages;
    // End of variables declaration//GEN-END:variables
    private File _defaultDir;
    private File _document;
    private PDFFile _pdf;
    private int _page;
    private int _zoom=100;

    /**
     * @return the _page
     */
    public int getPage() {
        return _page;
    }

    /**
     * @param page the _page to set
     */
    public void setPage(int page) {
        this._page = page;
        this.jPageNumber.setDouble(page);
        Image image=(new PdfPage(this._pdf,_page,100)).getImage();
        this.jImage1.setImage(image);
        int w=image.getWidth(this.jImage1);
        int h=image.getHeight(this.jImage1);
        Dimension d=new Dimension(w, h);
        this.jImage1.setMaximumSize(d);
        this.jImage1.setMaximumSize(d);
        this.jImage1.setPreferredSize(d);
        this.jImage1.setSize(d);
        this.jImage1.repaint();
    }

    /**
     * @return the _zoom
     */
    public int getZoom() {
        return _zoom;
    }

    /**
     * @param zoom the _zoom to set
     */
    public void setZoom(int zoom) {
        _zoom=zoom;
        double scale=zoom/100.0;
        this.jPageNumber.setDouble(_page);
        Image image=(new PdfPage(this._pdf,_page,zoom)).getImage();
        this.jImage1.setImage(image);
        int w=image.getWidth(this.jImage1);
        int h=image.getHeight(this.jImage1);
        Dimension d=new Dimension(Convert.toInt(w*scale), Convert.toInt(h*scale));
        System.out.println(scale);
        this.jImage1.setMaximumSize(d);
        this.jImage1.setMaximumSize(d);
        this.jImage1.setPreferredSize(d);
        this.jImage1.setSize(d);
        this.jImage1.setScaleWidth(scale);
        this.jImage1.setScaleHeight(scale);
        this.jImage1.repaint();
    }
}
